name: 'Dotenv Loader'
description: 'Load variables from .env file'
inputs:
  path:
    description: 'The path to the .env file (including file name)'
    required: true
    default: './.env'
  log-variables:
    description: 'Whether to log the variables to output or not'
    required: false
    default: 'false'
  mask-variables:
    description: 'Whether to mask the variables as secrets or not'
    required: false
    default: 'false'
  export-variables:
    description: 'Whether to export the variables to the environment or not'
    required: false
    default: 'true'
  keys-case:
    description: 'Transform keys case to lower, upper, or keep as it is with bypass'
    required: false
    default: 'lower'
outputs:
  generic:
    description: 'This command will have generic output variables based on .env'
runs:
  using: 'node20'
  main: 'dist/index.js'
